[config]
default_to_workspace = false

[tasks.set-env-local.env]
CAL2_PROMPT_CONFIG_FILE_PATH = "${CARGO_MAKE_WORKING_DIRECTORY}/.config/config.lua"

[tasks.run]
extend = "set-env-local"
command = "cargo"
args = ["run", "${@}"]

[tasks.build]
extend = "set-env-local"
command = "cargo"
args = ["build", "${@}"]

[tasks.check]
extend = "set-env-local"
command = "cargo"
args = ["check"]

[tasks.watch]
extend = "set-env-local"
run_task = [{ name = ["fmt", "clippy", "test"] }]
watch = true

[tasks.fmt]
extend = "set-env-local"
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.clippy]
extend = "set-env-local"
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.test]
extend = "set-env-local"
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
  "nextest",
  "--help",
] }
command = "cargo"
args = [
  "nextest",
  "run",
  "--workspace",
  "--status-level",
  "all",
  "--test-threads=1",
]

[tasks.install-nextest]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = ["nextest", "--help"] }

[tasks.coverage-ci]
extend = "set-env-local"
install_crate = { crate_name = "cargo-llvm-cov", binary = "cargo", test_arg = ["llvm-cov", "--help"] }
dependencies = ["install-nextest"]
command = "cargo"
args = [
  "llvm-cov",
  "--lcov",
  "--output-path",
  "lcov.info",
  "nextest",
]

[tasks.coverage-html]
extend = "set-env-local"
install_crate = { crate_name = "cargo-llvm-cov", binary = "cargo", test_arg = ["llvm-cov", "--help"] }
dependencies = ["install-nextest"]
command = "cargo"
args = [
  "llvm-cov",
  "--html",
  "nextest",
]

[tasks.clippy-ci]
run_task = { name = "clippy", fork = true, silent = true }

[tasks.test-ci]
run_task = { name = "test", fork = true, silent = true }

[tasks.coverage-ci-run]
run_task = { name = "coverage-ci", fork = true, silent = true }
